<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
<meta name="generator" content="pdoc 0.10.0" />
<title>sverchok.utils.modules.FreeCAD_utils API documentation</title>
<meta name="description" content="find the add-on version of this module at:
https://gist.github.com/yorikvanhavre/680156f59e2b42df8f5f5391cae2660b â€¦" />
<link rel="preload stylesheet" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/11.0.1/sanitize.min.css" integrity="sha256-PK9q560IAAa6WVRRh76LtCaI8pjTJ2z11v0miyNNjrs=" crossorigin>
<link rel="preload stylesheet" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/11.0.1/typography.min.css" integrity="sha256-7l/o7C8jubJiy74VsKTidCy1yBkRtiUGbVkYBylBqUg=" crossorigin>
<link rel="stylesheet preload" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/github.min.css" crossorigin>
<style>:root{--highlight-color:#fe9}.flex{display:flex !important}body{line-height:1.5em}#content{padding:20px}#sidebar{padding:30px;overflow:hidden}#sidebar > *:last-child{margin-bottom:2cm}.http-server-breadcrumbs{font-size:130%;margin:0 0 15px 0}#footer{font-size:.75em;padding:5px 30px;border-top:1px solid #ddd;text-align:right}#footer p{margin:0 0 0 1em;display:inline-block}#footer p:last-child{margin-right:30px}h1,h2,h3,h4,h5{font-weight:300}h1{font-size:2.5em;line-height:1.1em}h2{font-size:1.75em;margin:1em 0 .50em 0}h3{font-size:1.4em;margin:25px 0 10px 0}h4{margin:0;font-size:105%}h1:target,h2:target,h3:target,h4:target,h5:target,h6:target{background:var(--highlight-color);padding:.2em 0}a{color:#058;text-decoration:none;transition:color .3s ease-in-out}a:hover{color:#e82}.title code{font-weight:bold}h2[id^="header-"]{margin-top:2em}.ident{color:#900}pre code{background:#f8f8f8;font-size:.8em;line-height:1.4em}code{background:#f2f2f1;padding:1px 4px;overflow-wrap:break-word}h1 code{background:transparent}pre{background:#f8f8f8;border:0;border-top:1px solid #ccc;border-bottom:1px solid #ccc;margin:1em 0;padding:1ex}#http-server-module-list{display:flex;flex-flow:column}#http-server-module-list div{display:flex}#http-server-module-list dt{min-width:10%}#http-server-module-list p{margin-top:0}.toc ul,#index{list-style-type:none;margin:0;padding:0}#index code{background:transparent}#index h3{border-bottom:1px solid #ddd}#index ul{padding:0}#index h4{margin-top:.6em;font-weight:bold}@media (min-width:200ex){#index .two-column{column-count:2}}@media (min-width:300ex){#index .two-column{column-count:3}}dl{margin-bottom:2em}dl dl:last-child{margin-bottom:4em}dd{margin:0 0 1em 3em}#header-classes + dl > dd{margin-bottom:3em}dd dd{margin-left:2em}dd p{margin:10px 0}.name{background:#eee;font-weight:bold;font-size:.85em;padding:5px 10px;display:inline-block;min-width:40%}.name:hover{background:#e0e0e0}dt:target .name{background:var(--highlight-color)}.name > span:first-child{white-space:nowrap}.name.class > span:nth-child(2){margin-left:.4em}.inherited{color:#999;border-left:5px solid #eee;padding-left:1em}.inheritance em{font-style:normal;font-weight:bold}.desc h2{font-weight:400;font-size:1.25em}.desc h3{font-size:1em}.desc dt code{background:inherit}.source summary,.git-link-div{color:#666;text-align:right;font-weight:400;font-size:.8em;text-transform:uppercase}.source summary > *{white-space:nowrap;cursor:pointer}.git-link{color:inherit;margin-left:1em}.source pre{max-height:500px;overflow:auto;margin:0}.source pre code{font-size:12px;overflow:visible}.hlist{list-style:none}.hlist li{display:inline}.hlist li:after{content:',\2002'}.hlist li:last-child:after{content:none}.hlist .hlist{display:inline;padding-left:1em}img{max-width:100%}td{padding:0 .5em}.admonition{padding:.1em .5em;margin-bottom:1em}.admonition-title{font-weight:bold}.admonition.note,.admonition.info,.admonition.important{background:#aef}.admonition.todo,.admonition.versionadded,.admonition.tip,.admonition.hint{background:#dfd}.admonition.warning,.admonition.versionchanged,.admonition.deprecated{background:#fd4}.admonition.error,.admonition.danger,.admonition.caution{background:lightpink}</style>
<style media="screen and (min-width: 700px)">@media screen and (min-width:700px){#sidebar{width:30%;height:100vh;overflow:auto;position:sticky;top:0}#content{width:70%;max-width:100ch;padding:3em 4em;border-left:1px solid #ddd}pre code{font-size:1em}.item .name{font-size:1em}main{display:flex;flex-direction:row-reverse;justify-content:flex-end}.toc ul ul,#index ul{padding-left:1.5em}.toc > ul > li{margin-top:.5em}}</style>
<style media="print">@media print{#sidebar h1{page-break-before:always}.source{display:none}}@media print{*{background:transparent !important;color:#000 !important;box-shadow:none !important;text-shadow:none !important}a[href]:after{content:" (" attr(href) ")";font-size:90%}a[href][title]:after{content:none}abbr[title]:after{content:" (" attr(title) ")"}.ir a:after,a[href^="javascript:"]:after,a[href^="#"]:after{content:""}pre,blockquote{border:1px solid #999;page-break-inside:avoid}thead{display:table-header-group}tr,img{page-break-inside:avoid}img{max-width:100% !important}@page{margin:0.5cm}p,h2,h3{orphans:3;widows:3}h1,h2,h3,h4,h5,h6{page-break-after:avoid}}</style>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js" integrity="sha256-Uv3H6lx7dJmRfRvH8TH6kJD1TSK1aFcwgx+mdg3epi8=" crossorigin></script>
<script>window.addEventListener('DOMContentLoaded', () => hljs.initHighlighting())</script>
</head>
<body>
<main>
<article id="content">
<header>
<h1 class="title">Module <code>sverchok.utils.modules.FreeCAD_utils</code></h1>
</header>
<section id="section-intro">
<p>find the add-on version of this module at:
<a href="https://gist.github.com/yorikvanhavre/680156f59e2b42df8f5f5391cae2660b">https://gist.github.com/yorikvanhavre/680156f59e2b42df8f5f5391cae2660b</a></p>
<p>reproduced large parts with generous permission, includes modifications for convenience</p>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">&#34;&#34;&#34;
find the add-on version of this module at:
https://gist.github.com/yorikvanhavre/680156f59e2b42df8f5f5391cae2660b

reproduced large parts with generous permission, includes modifications for convenience
&#34;&#34;&#34;
from types import SimpleNamespace
import sys, bpy, xml.sax, zipfile, os
from bpy_extras.node_shader_utils import PrincipledBSDFWrapper
from mathutils import Quaternion, Matrix 

from sverchok.dependencies import FreeCAD
if FreeCAD:

    def rounded(rgba, level=5):
        return tuple(round(c, level) for c in rgba)

    def cleanup(faces, faces_data):
        &#34;&#34;&#34;
        this avoids the following bmesh exception:

           faces.new(verts): face already exists

        &#34;&#34;&#34;
        faces_set = set()
        
        new_faces = []
        new_faces_data = []
        good_face = new_faces.append
        good_face_data = new_faces_data.append
        
        for idx, face in enumerate(faces):
            proposed_face = tuple(sorted(face))
            if proposed_face in faces_set:
                continue
            else:
                faces_set.add(proposed_face)
                good_face(face)
                if faces_data:
                    color = faces_data[0] if len(faces_data) == 1 else faces_data[idx]  
                    good_face_data(color)
                
        return new_faces, new_faces_data


    from sverchok.utils.decorators import duration
    import Part

    class FreeCAD_xml_handler(xml.sax.ContentHandler):

        &#34;&#34;&#34;A XML handler to process the FreeCAD GUI xml data&#34;&#34;&#34;

        # this creates a dictionary where each key is a FC object name,
        # and each value is a dictionary of property:value pairs

        def __init__(self):

            self.guidata = {}
            self.current = None
            self.properties = {}
            self.currentprop = None
            self.currentval = None

        # Call when an element starts

        def startElement(self, tag, attributes):

            if tag == &#34;ViewProvider&#34;:
                self.current = attributes[&#34;name&#34;]
            elif tag == &#34;Property&#34;:
                name = attributes[&#34;name&#34;]
                if name in [&#34;Visibility&#34;, &#34;ShapeColor&#34;, &#34;Transparency&#34;, &#34;DiffuseColor&#34;]:
                    self.currentprop = name
            elif tag == &#34;Bool&#34;:
                if attributes[&#34;value&#34;] == &#34;true&#34;:
                    self.currentval = True
                else:
                    self.currentval = False
            elif tag == &#34;PropertyColor&#34;:
                c = int(attributes[&#34;value&#34;])
                r = float((c&gt;&gt;24)&amp;0xFF)/255.0
                g = float((c&gt;&gt;16)&amp;0xFF)/255.0
                b = float((c&gt;&gt;8)&amp;0xFF)/255.0
                self.currentval = (r,g,b)
            elif tag == &#34;Integer&#34;:
                self.currentval = int(attributes[&#34;value&#34;])
            elif tag == &#34;Float&#34;:
                self.currentval = float(attributes[&#34;value&#34;])
            elif tag == &#34;ColorList&#34;:
                self.currentval = attributes[&#34;file&#34;]

        # Call when an elements ends

        def endElement(self, tag):

            if tag == &#34;ViewProvider&#34;:
                if self.current and self.properties:
                    self.guidata[self.current] = self.properties
                    self.current = None
                    self.properties = {}
            elif tag == &#34;Property&#34;:
                if self.currentprop and (self.currentval != None):
                    self.properties[self.currentprop] = self.currentval
                    self.currentprop = None
                    self.currentval = None

    def get_guidata(filename):

        # check if we have a GUI document
        guidata = {}
        with zipfile.ZipFile(filename) as zdoc:

            if &#34;GuiDocument.xml&#34; in zdoc.namelist():

                with zdoc.open(&#34;GuiDocument.xml&#34;) as gf:
 
                    guidata = gf.read()
                    Handler = FreeCAD_xml_handler()
                    xml.sax.parseString(guidata, Handler)
                    guidata = Handler.guidata
                    for key, properties in guidata.items():

                        if (diffuse_file := properties.get(&#34;DiffuseColor&#34;)):
                        
                            with zdoc.open(diffuse_file) as df:
                                buf = df.read()
                                # first 4 bytes are the array length, then each group of 4 bytes is abgr
                                # overwrite file reference with color data.
                                cols = [(buf[i*4+3], buf[i*4+2], buf[i*4+1], buf[i*4]) for i in range(1,int(len(buf)/4))]
                                guidata[key][&#34;DiffuseColor&#34;] = cols

        return guidata


    def hascurves(shape):
        for e in shape.Edges:
            if not isinstance(e.Curve, (Part.Line, Part.LineSegment)): return True
        return False

    @duration
    def import_fcstd(
        filename,
        update=False,
        placement=True,
        tessellation=1.0,
        skiphidden=True,
        scale=1.0,
        sharemats=True,
        remove_duplicate_faces=True):

        guidata = get_guidata(filename)

        doc = FreeCAD.open(filename)
        docname = doc.Name
        if not doc:
            print(&#34;Unable to open the given FreeCAD file&#34;)
            return

        matdatabase = {} # to store reusable materials
                         #
                         # {(r, g, b, a): {}}
                         #
        obj_data = []

        for obj in doc.Objects:

            if skiphidden:
                if obj.Name in guidata:
                    if &#34;Visibility&#34; in guidata[obj.Name]:
                        if guidata[obj.Name][&#34;Visibility&#34;] == False:
                            continue

            verts = []
            vdict = dict() # maybe we gain some speed in lookups.
            edges = []
            faces = []
            add_face = faces.append # alias increase speed
            matindex = [] # face to material relationship
            faceedges = [] # a placeholder to store edges that belong to a face
            name = &#34;Unnamed&#34;
            polycolors = []

            if obj.isDerivedFrom(&#34;Part::Feature&#34;):

                # create mesh from shape
                shape = obj.Shape
                if placement:
                    placement = obj.Placement
                    shape = obj.Shape.copy()
                    shape.Placement = placement.inverse().multiply(shape.Placement)

                if shape.Faces:

                    # write FreeCAD faces as polygons when possible
                    for face in shape.Faces:
                        
                        if (len(face.Wires) &gt; 1) or (not isinstance(face.Surface, Part.Plane)) or hascurves(face):
                            # face has holes or is curved, so we need to triangulate it
                            rawdata = face.tessellate(tessellation)
                            
                            for v in rawdata[0]:
                                if (v1 := (v.x, v.y, v.z)) not in vdict:
                                    vdict[v1] = len(vdict)
                            
                            for f in rawdata[1]:
                                raw = rawdata[0]
                                nf = [vdict[(nv.x, nv.y, nv.z)] for nv in [raw[vi] for vi in f]]
                                add_face(nf)

                            matindex.append(len(rawdata[1]))
                        
                        else:
                        
                            f = []
                            ov = face.OuterWire.OrderedVertexes
                        
                            for v in ov:

                                if (vec := (v.X, v.Y, v.Z)) not in vdict:
                                    vdict[vec] = len(vdict)
                                    f.append(len(vdict) - 1)
                                else:
                                    f.append(vdict[(v.X, v.Y, v.Z)])
                        
                            # FreeCAD doesn&#39;t care about verts order. Make sure our loop goes clockwise
                            c = face.CenterOfMass
                            v1 = ov[0].Point.sub(c)
                            v2 = ov[1].Point.sub(c)
                            n = face.normalAt(0,0)
                            if (v1.cross(v2)).getAngle(n) &gt; 1.57:
                                f.reverse() # inverting verts order if the direction is couterclockwise
                            
                            add_face(f)
                            matindex.append(1)
                        
                        for e in face.Edges:
                            faceedges.append(e.hashCode())

                for edge in shape.Edges:
                    # Treat remaining edges (that are not in faces)
                    if not (edge.hashCode() in faceedges):
                        
                        if hascurves(edge):
                            dv = edge.discretize(9) #TODO use tessellation value
                            for i in range(len(dv)-1):
                                dv1 = (dv[i].x,   dv[i].y,   dv[i].z)
                                dv2 = (dv[i+1].x, dv[i+1].y, dv[i+1].z)
                                if dv1 not in vdict:
                                    vdict[dv1] = len(vdict)
                                if dv2 not in vdict:
                                    vdict[dv2] = len(vdict)
                                edges.append([vdict[dv1], vdict[dv2]])
                        
                        else:
                        
                            e = []
                            for vert in edge.Vertexes:
                                v = (vert.X,vert.Y,vert.Z)
                                if v not in vdict: vdict[v] = len(vdict)
                                e.append(vdict[v])

                            edges.append(e)

                verts = list(vdict.keys())

            elif obj.isDerivedFrom(&#34;Mesh::Feature&#34;):
                # convert freecad mesh to blender mesh
                mesh = obj.Mesh
                if placement:
                    placement = obj.Placement
                    mesh = obj.Mesh.copy() # in meshes, this zeroes the placement
                t = mesh.Topology
                verts = [(v.x, v.y, v.z) for v in t[0]]
                faces = t[1]

            current_obj = SimpleNamespace(verts=verts, edges=edges, faces=faces, matindex=matindex, plac=None, faceedges=faceedges, name=obj.Name)
            current_obj.matrix = Matrix()
            current_obj.loc = (0.0, 0.0, 0.0)
            current_obj.polycolors = polycolors

            if placement:            
                current_obj.loc = placement.Base.multiply(scale)[:]
                if placement.Rotation.Angle:
                    # FreeCAD Quaternion is XYZW while Blender is WXYZ
                    x, y, z, w = placement.Rotation.Q
                    new_quaternion = Quaternion((w, x, y, z))
                    current_obj.matrix = new_quaternion.to_matrix().to_4x4()
                    current_obj.loc = placement.Base.multiply(scale)[:]

            if verts and (faces or edges):

                if not obj.Name in guidata: continue

                if matindex and (&#34;DiffuseColor&#34; in guidata[obj.Name]) and (len(matindex) == len(guidata[obj.Name][&#34;DiffuseColor&#34;])):

                    # we have per-face materials. Create new mats and attribute faces to them
                    fi = 0
                    for i in range(len(matindex)):
                        
                        # DiffuseColor stores int values, Blender use floats
                        guid_objname_diffcol = guidata[obj.Name][&#34;DiffuseColor&#34;]
                        rgba = tuple([float(x) / 255.0 for x in guid_objname_diffcol[i]])
                        
                        # FreeCAD stores transparency, not alpha
                        alpha = 1.0
                        if rgba[3] &gt; 0: alpha = 1.0 - rgba[3]
                        rgba = rgba[:3] + (alpha,)
                        rgba = rounded(rgba)

                        for fj in range(matindex[i]):
                            polycolors.append(rgba)

                        fi += matindex[i]

                else:

                    # one material for the whole object
                    if (transparency := guidata[obj.Name].get(&#34;Transparency&#34;, 1.0)) &gt; 0:
                        alpha = (100 - transparency) / 100.0
                    else:
                        alpha = 1.0

                    rgb = guidata[obj.Name].get(&#34;ShapeColor&#34;, (0.5, 0.5, 0.5))
                    rgba = rgb + (alpha,)
                    rgba = rounded(rgba)
                    polycolors.append(rgba)


            if remove_duplicate_faces and current_obj.faces:
                current_obj.faces, current_obj.polycolors = cleanup(current_obj.faces, current_obj.polycolors)

            obj_data.append(current_obj)


        FreeCAD.closeDocument(docname)
        print(&#34;Import finished without errors&#34;)

        return obj_data</code></pre>
</details>
</section>
<section>
</section>
<section>
</section>
<section>
</section>
<section>
</section>
</article>
<nav id="sidebar">
<h1>Index</h1>
<div class="toc">
<ul></ul>
</div>
<ul id="index">
<li><h3>Super-module</h3>
<ul>
<li><code><a title="sverchok.utils.modules" href="index.html">sverchok.utils.modules</a></code></li>
</ul>
</li>
</ul>
</nav>
</main>
<footer id="footer">
<p>Generated by <a href="https://pdoc3.github.io/pdoc" title="pdoc: Python API documentation generator"><cite>pdoc</cite> 0.10.0</a>.</p>
</footer>
</body>
</html>